Repository prometheus/prometheus, pull requests merged in 2020-08, with the labels that each got.

#5390 Updated documentation
  docs/configuration/configuration.md
Labels: stale

#7733 tsdb: Save allocations on labels by re-using label array
  tsdb/querier.go
Labels: funcbench

#7708 Add additional tag/log to rules Manager Eval trace span.
  rules/manager.go
Labels: component/rules

#7747 storage/remote: split httpclient name.
  storage/remote/client.go
Labels: component/remote storage

#7857 Release 2.21.0-rc.0
  CHANGELOG.md
  VERSION
Labels: prombench

#6869 docs: minor corrections to the docker documentation
  docs/installation.md
Labels: stale

#6879 add key to StatusWithStatusIndicator component in loop
  web/ui/react-app/src/pages/status/Status.tsx
Labels: stale
