Repository prometheus/prometheus, pull requests merged in 2024-02, with the labels that each got.

#13337 Pod status changes not discovered by Kube Endpoints SD
  discovery/kubernetes/endpoints.go
  discovery/kubernetes/endpoints_test.go
  discovery/kubernetes/endpointslice.go
  discovery/kubernetes/kubernetes.go
  discovery/kubernetes/pod.go
Labels: prombench

#8106 Small improvements, add const, remove one tab, remove copypasta
  tsdb/index/index.go
Labels: component/tsdb, stale

#13448 Proposal to improve FPointSlice and HPointSlice allocation.
  promql/bench_test.go
  promql/engine.go
Labels: prombench

#8085 Enforce chunks ordering when writing index.
  tsdb/docs/format/index.md
  tsdb/index/index.go
  tsdb/index/index_test.go
Labels: component/tsdb, stale

#8492 updates to grammer and spelling
  docs/querying/basics.md
Labels: stale

#13536 promql: faster range-query of label_replace and label_join
  promql/engine.go
  promql/functions.go
Labels: kind/optimization
