Repository prometheus/prometheus, pull requests merged in 2024-07, with the labels that each got.

#14371 OTLP: Document histogram conversion methods / clean up code a bit
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms.go
Labels: kind/enhancement, component/otlp

#14396 TSDB: Simplify OOO Select by copying the head chunk
  tsdb/chunks/chunks.go
  tsdb/head_read.go
  tsdb/head_read_test.go
  tsdb/ooo_head_read.go
  tsdb/ooo_head_read_test.go
Labels: prombench

#12503 feat: add limitk() and limit_ratio() operators
  docs/querying/examples.md
  docs/querying/operators.md
  promql/bench_test.go
  promql/engine.go
  promql/engine_test.go
  promql/parser/generated_parser.y
  promql/parser/generated_parser.y.go
  promql/parser/lex.go
  promql/parser/parse.go
  promql/promql_test.go
  promql/promqltest/testdata/limit.test
  util/annotations/annotations.go
  web/ui/module/codemirror-promql/src/complete/promql.terms.ts
  web/ui/module/codemirror-promql/src/parser/parser.ts
  web/ui/module/lezer-promql/src/highlight.js
  web/ui/module/lezer-promql/src/promql.grammar
  web/ui/module/lezer-promql/src/tokens.js
Labels: priority/Pmaybe

#14322 TSDB: Lock around access to labels in head under -tags dedupelabels
  tsdb/head.go
  tsdb/head_append.go
  tsdb/head_dedupelabels.go
  tsdb/head_other.go
  tsdb/head_read.go
  tsdb/head_wal.go
  tsdb/ooo_head_read.go
Labels: prombench

#14424 Fix a couple of comments
  tsdb/chunkenc/xor.go
  tsdb/record/record.go
Labels: kind/cleanup, component/tsdb

#9138 Making durations and number literals the same
  docs/querying/basics.md
  promql/parser/generated_parser.y
  promql/parser/generated_parser.y.go
  promql/parser/lex.go
  promql/parser/parse_test.go
  promql/promqltest/testdata/at_modifier.test
  promql/promqltest/testdata/functions.test
  promql/promqltest/testdata/staleness.test
  promql/promqltest/testdata/subquery.test
Labels: stale

#14467 golangci-lint: Don't use deprecated config params
  .golangci.yml
Labels: kind/cleanup

#14420 Fix web.cors.origin in command-line/prometheus.md
  docs/command-line/prometheus.md
  util/documentcli/documentcli.go
Labels: component/documentation

#14200 OTLP Translator prometheusremotewrite: Support resource attribute promotion
  CHANGELOG.md
  config/config.go
  config/config_test.go
  config/testdata/conf.good.yml
  config/testdata/otlp_sanitize_resource_attributes.bad.yml
  config/testdata/otlp_sanitize_resource_attributes.good.yml
  docs/configuration/configuration.md
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
  storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
  storage/remote/write_handler.go
  storage/remote/write_test.go
  web/api/v1/api.go
  web/api/v1/api_test.go
Labels: kind/feature, component/otlp

#14470 Labels: use single byte as separator - small speedup
  model/labels/labels.go
  model/labels/labels_common.go
  model/labels/labels_dedupelabels.go
  model/labels/labels_stringlabels.go
  model/labels/sharding.go
  model/labels/sharding_dedupelabels.go
  model/labels/sharding_stringlabels.go
Labels: kind/optimization

#14498 Prepare release 2.54.0-rc.0
  CHANGELOG.md
  VERSION
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
  web/ui/react-app/package.json
Labels: prombench
