Repository prometheus/prometheus, pull requests merged in 2024-06, with the labels that each got.

#14199 tsdb/index: Fix number of series in TestReader_PostingsForLabelMatchingHonorsContextCancel
  tsdb/index/index_test.go
Labels: component/tests

#13286 `MemPostings.Delete()`: reduce locking/unlocking
  tsdb/index/postings.go
  tsdb/index/postings_test.go
Labels: prombench

#14285 Tune default GOGC
  config/config.go
  docs/configuration/configuration.md
Labels: prombench

#13434 storage: don't wrap single querier in merge-queriers
  storage/merge.go
  storage/merge_test.go
Labels: kind/optimization
