Repository prometheus/prometheus, pull requests merged in 2024-11, with the labels that each got.

#15251 bugfix: Fix otlp translator switching colons to underscores in suffix adding mode
  storage/remote/otlptranslator/prometheus/normalize_name.go
  storage/remote/otlptranslator/prometheus/normalize_name_test.go
Labels: kind/bug, component/otlp, area/opentelemetry

#15314 otlptranslator: Harmonize non-UTF8 sanitization w/ naming rules.
  CHANGELOG.md
  storage/remote/otlptranslator/prometheus/normalize_label.go
  storage/remote/otlptranslator/prometheus/normalize_name.go
  storage/remote/otlptranslator/prometheus/normalize_name_test.go
  storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
Labels: kind/bug, component/otlp, area/opentelemetry

#15316 Revert "Fix `MemPostings.Add` and `MemPostings.Get` data race (#15141)"
  tsdb/head_bench_test.go
  tsdb/index/postings.go
  tsdb/index/postings_test.go
Labels: prombench

#15351 Fix scrape failure logs
  scrape/scrape.go
Labels: backport-3.0

#15355 Update prometheus/common
  go.mod
  go.sum
  util/logging/file_test.go
Labels: backport-3.0

#15331 promql parser: Use a function to determine if an aggregation function is experimental
  promql/parser/lex.go
  promql/parser/parse.go
Labels: kind/cleanup, component/promql

#14144 tsdb.PostingsForMatchers: Optimize inverse matching
  tsdb/block.go
  tsdb/head_read.go
  tsdb/index/index.go
  tsdb/index/index_test.go
  tsdb/index/postings.go
  tsdb/index/postings_test.go
  tsdb/ooo_head_read.go
  tsdb/querier.go
  tsdb/querier_test.go
Labels: component/tsdb, kind/optimization

#15416 OTLP receiver: Convert also metric metadata
  CHANGELOG.md
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
  storage/remote/otlptranslator/prometheusremotewrite/otlp_to_openmetrics_metadata.go
  storage/remote/otlptranslator/prometheusremotewrite/timeseries.go
  storage/remote/write_handler.go
Labels: kind/enhancement, area/opentelemetry

#15424 Upgrade to golangci-lint v1.62.0
  .github/workflows/ci.yml
  Makefile.common
  documentation/examples/remote_storage/remote_storage_adapter/opentsdb/client_test.go
  model/labels/labels_test.go
  promql/histogram_stats_iterator_test.go
  scrape/scrape_test.go
  scripts/golangci-lint.yml
  storage/remote/codec_test.go
  storage/remote/intern_test.go
  storage/series_test.go
  tsdb/index/index_test.go
  web/api/v1/api_test.go
Labels: kind/cleanup

#15429 promqltest: Complete the tests for info annotations
  promql/engine_test.go
  promql/promqltest/test.go
  promql/promqltest/testdata/aggregators.test
  promql/promqltest/testdata/at_modifier.test
  promql/promqltest/testdata/functions.test
  promql/promqltest/testdata/histograms.test
  promql/promqltest/testdata/name_label_dropping.test
  promql/promqltest/testdata/operators.test
  promql/promqltest/testdata/selectors.test
  promql/promqltest/testdata/subquery.test
Labels: component/promql

#15431 promql: Fix subqueries to be really left-open
  promql/engine.go
  promql/engine_test.go
Labels: backport-3.0

#15356 rules.NewGroup: Fix when no logger is passed
  rules/group.go
  rules/group_test.go
Labels: kind/bug, component/rules, backport-3.0

#15434 fix!: stop unbounded memory usage from query log
  promql/engine.go
  promql/engine_test.go
  scrape/scrape.go
  util/logging/file.go
  util/logging/file_test.go
Labels: backport-3.0

#14936 [DOCS] Improve description of WAL record format
  tsdb/docs/format/wal.md
Labels: stale

#15455 [PERF] TSDB: Cache all symbols for compaction
  tsdb/index/index.go
Labels: prombench

#15399 Add support for utf8 names on /v1/label/:name/values endpoint
  docs/querying/api.md
  promql/parser/generated_parser.y
  promql/parser/generated_parser.y.go
  web/api/v1/api.go
  web/api/v1/api_test.go
Labels: backport-3.0

#15426 [PERF] TSDB: MemPostings: keep a map of label values slices
  tsdb/index/postings.go
Labels: prombench
