Repository prometheus/prometheus, pull requests merged in 2024-10, with the labels that each got.

#14976 Prepare 3.0.0-beta.1
  CHANGELOG.md
  VERSION
  web/ui/mantine-ui/package.json
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
Labels: prombench

#14495 [FEATURE] PromQL: Add experimental info function MVP
  CHANGELOG.md
  docs/querying/functions.md
  promql/bench_test.go
  promql/engine.go
  promql/functions.go
  promql/info.go
  promql/info_test.go
  promql/parser/ast.go
  promql/parser/functions.go
  promql/parser/parse.go
  promql/parser/parse_test.go
  web/ui/module/codemirror-promql/src/complete/promql.terms.ts
  web/ui/module/codemirror-promql/src/parser/parser.test.ts
  web/ui/module/codemirror-promql/src/parser/parser.ts
  web/ui/module/codemirror-promql/src/types/function.ts
  web/ui/module/lezer-promql/src/promql.grammar
Labels: component/promql, kind/feature, area/opentelemetry

#15172 chore(deps): update client_golang from 1.20.4 to 1.20.5
  go.mod
  go.sum
Labels: dependencies

#14657 config: remove expand-external-labels flag in release 3.0
  cmd/prometheus/main.go
  cmd/promtool/main.go
  cmd/promtool/sd.go
  config/config.go
  config/config_test.go
  docs/configuration/configuration.md
  docs/feature_flags.md
  scrape/scrape_test.go
Labels: component/config, kind/breaking

#13883 Disallowing configure AM with the v1 api
  cmd/promtool/testdata/config_with_service_discovery_files.yml
  config/config.go
  config/config_test.go
  config/testdata/config_with_deprecated_am_api_config.yml
  notifier/notifier.go
  notifier/notifier_test.go
Labels: kind/breaking

#15136 scrape: provide a fallback format
  CHANGELOG.md
  config/config.go
  config/config_test.go
  config/testdata/conf.good.yml
  config/testdata/scrape_config_files_fallback_scrape_protocol1.bad.yml
  config/testdata/scrape_config_files_fallback_scrape_protocol2.bad.yml
  docs/configuration/configuration.md
  model/textparse/interface.go
  model/textparse/interface_test.go
  promql/fuzz.go
  scrape/scrape.go
  scrape/scrape_test.go
Labels: component/scraping, kind/change, kind/breaking

#15164 feat: normalize "le" and "quantile" labels values upon ingestion
  docs/feature_flags.md
  model/textparse/interface.go
  model/textparse/openmetricsparse.go
  model/textparse/openmetricsparse_test.go
  model/textparse/promparse.go
  model/textparse/promparse_test.go
Labels: kind/breaking

#15197 docs: add keep_firing_for in alerting rules
  docs/configuration/alerting_rules.md
Labels: component/documentation

#14983 fix(storage/mergeQuerier): fix a data race
  storage/merge.go
  tsdb/querier_test.go
Labels: prombench

#15231 tsdb.CircularExemplarStorage: Avoid racing
  tsdb/exemplar.go
  tsdb/exemplar_test.go
Labels: kind/bug, component/tsdb
