Repository prometheus/prometheus, pull requests merged in 2024-12, with the labels that each got.

#14638 promqltest: run each eval command in a subtest
  promql/promqltest/test.go
  promql/promqltest/test_test.go
Labels: stale

#14637 Reword storage docs on corruption issues
  docs/storage.md
Labels: stale

#15537 OTLP receiver: Don't call NormalizeLabel in `NoUTF8EscapingWithSuffixes` mode
  storage/remote/otlptranslator/prometheus/normalize_label.go
  storage/remote/otlptranslator/prometheus/normalize_label_test.go
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
Labels: component/otlp

#15684 Fix bug in `lbl!~".+"` postings for matchers shortcut
  tsdb/querier.go
  tsdb/querier_test.go
Labels: kind/bug, component/tsdb

#15699 Prepare release 3.1.0
  CHANGELOG.md
  VERSION
  web/ui/mantine-ui/package.json
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
Labels: prombench

#15261 Scraping: stop storing discovered labels
  cmd/promtool/sd.go
  scrape/manager_test.go
  scrape/scrape.go
  scrape/scrape_test.go
  scrape/target.go
  scrape/target_test.go
  web/api/v1/api.go
  web/api/v1/api_test.go
Labels: prombench, kind/optimization

#15709 otlptranslator: Remove unused function TrimPromSuffixes
  storage/remote/otlptranslator/prometheus/normalize_name.go
  storage/remote/otlptranslator/prometheus/normalize_name_test.go
Labels: kind/cleanup, component/otlp

#15636 tsdb: export checkpointPrefix constant
  tsdb/db.go
  tsdb/wlog/checkpoint.go
Labels: kind/cleanup

#15447 docs: update required go version in readme to 1.22
  README.md
Labels: kind/cleanup

#15733 OTLP receiver: Optimize by initializing regexps at program start
  storage/remote/otlptranslator/prometheus/normalize_name.go
Labels: kind/enhancement, area/opentelemetry
