Repository prometheus/prometheus, pull requests merged in 2024-03, with the labels that each got.

#13729 Cut v2.51.0-rc.0
  CHANGELOG.md
  VERSION
  discovery/azure/azure.go
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
  web/ui/react-app/package.json
Labels: prombench

#13742 [ENHANCEMENT] TSDB: Check CRC without allocating
  tsdb/chunks/head_chunks.go
Labels: kind/optimization

#13673 labels: optimize String method
  model/labels/labels_common.go
  model/labels/labels_test.go
Labels: kind/optimization

#9633 Fix retention boundary so 2h retention deletes blocks right at the 2h boundary
  CHANGELOG.md
  tsdb/db.go
  tsdb/db_test.go
Labels: stale

#12933 Check for duplicated series on a scrape
  scrape/scrape.go
  scrape/scrape_test.go
Labels: prombench

#13790 tsdb.BeyondTimeRetention: Fix comment and test at retention duration
  tsdb/db.go
  tsdb/db_test.go
Labels: component/tsdb

#13844 tsdb/wlog.Checkpoint: Handle also float histograms
  tsdb/wlog/checkpoint.go
  tsdb/wlog/checkpoint_test.go
Labels: kind/bug, component/tsdb
