Repository prometheus/prometheus, pull requests merged in 2025-07, with the labels that each got.

#16806 Consolidate around prometheus/common/model.ValidationScheme
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  scrape/scrape.go
  scrape/scrape_test.go
Labels: kind/cleanup

#16737 OTLP receiver: Generate `target_info` samples between the earliest and latest samples per resource
  CHANGELOG.md
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
  storage/remote/write_handler.go
  web/api/v1/api.go
  web/api/v1/errors_test.go
  web/web.go
Labels: kind/bug, area/opentelemetry

#16423 storage: add projection fields to select hints
  storage/interface.go
Labels: stale

#16332 fix: unlock of unlocked mutex
  tsdb/head_append.go
  tsdb/head_test.go
Labels: priority/P1

#16848 chore(tsdb): add a few more testcases for unlock of unlocked mtx 16332
  tsdb/head_test.go
Labels: priority/P3
