Repository prometheus/prometheus, pull requests merged in 2025-01, with the labels that each got.

#14518 TSDB: Optimization: Merge postings using concrete type
  tsdb/head_read.go
  tsdb/head_test.go
  tsdb/index/postings.go
  tsdb/index/postings_test.go
Labels: kind/optimization

#15721 template: Use cases.Title instead of deprecated strings.Title
  docs/configuration/template_reference.md
  template/template.go
Labels: kind/cleanup

#15467 feat(nhcb): support custom buckets in native histograms in the WAL/WBL
  model/textparse/nhcbparse.go
  tsdb/agent/db.go
  tsdb/agent/db_test.go
  tsdb/db_test.go
  tsdb/docs/format/wal.md
  tsdb/head_append.go
  tsdb/head_test.go
  tsdb/head_wal.go
  tsdb/ooo_head_read_test.go
  tsdb/record/record.go
  tsdb/record/record_test.go
  tsdb/testutil.go
  tsdb/tsdbutil/histogram.go
  tsdb/wlog/checkpoint.go
  tsdb/wlog/checkpoint_test.go
  tsdb/wlog/watcher.go
  tsdb/wlog/watcher_test.go
Labels: prombench

#15664 otlp/translator: Use separate function for metric names with UTF8 characters
  storage/remote/otlptranslator/prometheus/helpers_from_stdlib.go
  storage/remote/otlptranslator/prometheus/metric_name_builder.go
  storage/remote/otlptranslator/prometheus/metric_name_builder_test.go
  storage/remote/otlptranslator/prometheus/normalize_name_test.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
Labels: kind/bug, area/opentelemetry

#15722 Fix issues raised by staticcheck
  cmd/prometheus/main.go
  cmd/promtool/main.go
  promql/promqltest/test.go
  scrape/target.go
  storage/remote/metadata_watcher.go
  storage/remote/queue_manager.go
  tsdb/wlog/watcher.go
  web/api/v1/api.go
  web/api/v1/api_test.go
Labels: kind/cleanup

#15719 promtool: Support linting of scrape interval
  CHANGELOG.md
  cmd/promtool/main.go
  cmd/promtool/main_test.go
  cmd/promtool/testdata/prometheus-config.lint.too_long_scrape_interval.yml
  docs/command-line/promtool.md
Labels: kind/enhancement, component/promtool

#15832 scrape: Fix metadata in WAL not working for histograms and summaries.
  scrape/helpers_test.go
  scrape/scrape.go
  scrape/scrape_test.go
  scrape/target.go
  storage/remote/metadata_watcher_test.go
  storage/remote/queue_manager.go
  storage/remote/queue_manager_test.go
  web/api/v1/api.go
  web/api/v1/api_test.go
Labels: prombench

#15894 Apply npm audit fix to react-app
  web/ui/react-app/package-lock.json
Labels: dependencies, javascript, old-react-ui
