Repository prometheus/prometheus, pull requests merged in 2025-08, with the labels that each got.

#16970 repo sync: allow manual triggering
  .github/workflows/repo_sync.yml
Labels: area/ci-cd

#13971 Improving "Sparse postings" intersection
  tsdb/index/postings.go
  tsdb/querier_bench_test.go
Labels: stale

#17029 TSDB: use timestamps rather than WAL segment numbers to track how long deleted series should be retained in checkpoints
  tsdb/agent/db.go
  tsdb/db_test.go
  tsdb/head.go
  tsdb/head_test.go
  tsdb/head_wal.go
  tsdb/wlog/checkpoint.go
  tsdb/wlog/checkpoint_test.go
  tsdb/wlog/watcher_test.go
Labels: prombench
