Repository prometheus/prometheus, pull requests merged in 2025-05, with the labels that each got.

#16434 Prepare 3.3.1
  CHANGELOG.md
  VERSION
  cmd/prometheus/main.go
  cmd/prometheus/main_test.go
  cmd/promtool/main.go
  cmd/promtool/main_test.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  model/labels/labels_common.go
  model/labels/labels_test.go
  model/relabel/relabel.go
  model/textparse/openmetricsparse_test.go
  model/textparse/promparse_test.go
  promql/parser/parse_test.go
  promql/parser/printer_test.go
  promql/promqltest/test.go
  scrape/manager_test.go
  scrape/scrape_test.go
  storage/remote/codec_test.go
  storage/remote/write_handler.go
  util/logging/file.go
  web/api/v1/api_test.go
  web/ui/mantine-ui/package.json
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
Labels: prombench

#16368 Fix linting issues found by golangci-lint v2.0.2
  .golangci.yml
  cmd/prometheus/main_test.go
  cmd/prometheus/query_log_test.go
  cmd/promtool/main_test.go
  cmd/promtool/unittest.go
  discovery/aws/lightsail.go
  discovery/consul/consul_test.go
  discovery/kubernetes/pod.go
  discovery/linode/linode.go
  discovery/manager_test.go
  discovery/marathon/marathon_test.go
  discovery/moby/docker.go
  discovery/scaleway/instance.go
  discovery/uyuni/uyuni.go
  documentation/examples/remote_storage/remote_storage_adapter/main.go
  documentation/examples/remote_storage/remote_storage_adapter/opentsdb/tagvalue.go
  model/histogram/float_histogram.go
  model/labels/labels_test.go
  prompb/io/prometheus/client/decoder.go
  prompb/rwcommon/codec_test.go
  promql/bench_test.go
  promql/engine.go
  promql/parser/lex.go
  rules/manager_test.go
  scrape/scrape_test.go
  scrape/target.go
  storage/merge.go
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/queue_manager.go
  storage/remote/read.go
  storage/remote/read_handler_test.go
  storage/series_test.go
  tsdb/agent/db_test.go
  tsdb/chunks/head_chunks_test.go
  tsdb/compact_test.go
  tsdb/db_test.go
  tsdb/head_test.go
  tsdb/index/index_test.go
  tsdb/ooo_head_read_test.go
  tsdb/ooo_head_test.go
  tsdb/querier.go
  tsdb/querier_test.go
  tsdb/testutil.go
  util/annotations/annotations.go
  util/documentcli/documentcli.go
  util/stats/query_stats.go
  util/strutil/strconv.go
  web/web.go
  web/web_test.go
Labels: kind/cleanup

#16544 tsdb/errors.MultiError: support errors.As
  tsdb/errors/errors.go
  tsdb/errors/errors_test.go
Labels: kind/bug, component/tsdb

#16523 refactor: use slices.Contains to simplify code
  cmd/prometheus/main.go
  config/config.go
  discovery/kubernetes/kubernetes.go
  model/labels/labels_common.go
  model/labels/regexp.go
  rules/manager_test.go
  tsdb/index/postings.go
Labels: kind/cleanup

#16530 ci: address zizmor gh action vulnerabilities
  .github/workflows/buf-lint.yml
  .github/workflows/buf.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/container_description.yml
  .github/workflows/fuzzing.yml
  .github/workflows/prombench.yml
  .github/workflows/repo_sync.yml
Labels: area/security, area/ci-cd
