Repository prometheus/prometheus, pull requests merged in 2025-03, with the labels that each got.

#16180 Upgrade to Go v1.24
  .github/workflows/ci.yml
  .promu.yml
  Makefile.common
  promql/parser/lex.go
  promql/parser/parse.go
  scripts/golangci-lint.yml
  tsdb/errors/errors.go
  tsdb/ooo_head.go
  tsdb/ooo_head_read_test.go
Labels: prombench, area/build

#15850 Optionally translate OTel histograms to NHCB
  CHANGELOG.md
  config/config.go
  config/config_test.go
  config/testdata/otlp_convert_histograms_to_nhcb.good.yml
  docs/configuration/configuration.md
  prompb/codec.go
  prompb/types.pb.go
  prompb/types.proto
  storage/remote/otlptranslator/prometheusremotewrite/histograms.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
  storage/remote/write_handler.go
Labels: kind/feature, area/opentelemetry

#16250 Remove golangci-lint exclusions for OTLP code
  .golangci.yml
  storage/remote/otlptranslator/prometheusremotewrite/helper.go
  storage/remote/otlptranslator/prometheusremotewrite/helper_test.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms.go
  storage/remote/otlptranslator/prometheusremotewrite/histograms_test.go
  storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw_test.go
  storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
  storage/remote/otlptranslator/prometheusremotewrite/number_data_points_test.go
Labels: kind/cleanup

#16194 Prepare release 3.3.0-rc.0
  CHANGELOG.md
  VERSION
  web/ui/mantine-ui/package.json
  web/ui/module/codemirror-promql/package.json
  web/ui/module/lezer-promql/package.json
  web/ui/package-lock.json
  web/ui/package.json
Labels: prombench

#16348 web/ui: Update @babel dependencies to fix vulnerabilities
  web/ui/package-lock.json
Labels: component/ui, area/security
